# Generated by Django 5.2.5 on 2025-09-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Может отменять публикацию продукта'), ('can_change_description', 'Может изменять описание продукта')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='publication_status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('moderation', 'На модерации'), ('rejected', 'Отклонено')], default='moderation', max_length=20, verbose_name='Статус публикации'),
        ),
    ]
